sudo: required
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
services:
  - docker
before_install:
  - docker-compose up --no-start
  - docker-compose start
script:
  - docker inspect bangumi_crawler_1 | grep '"Running": true'
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
