sudo: required
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
env:
  - DOCKER_COMPOSE_VERSION=1.19.0
services:
  - docker
before_install:
  - docker-compose up --no-start
  - docker-compose start
script:
  - docker ps -a | grep 'angelmsger/bangumi-crawler' | grep 'Up'
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
