version: '3'
services:
  crawler:
    build: .
    image: bangumi-provider
    environment:
      - DB_ENABLE_AUTH=False
      - CACHE_ENABLE_AUTH=False
  redis:
    image: 'redis'
  mongo:
    image: 'mongo'
